import { Inter } from "next/font/google";
import "./globals.css";
import { BookMarkProvider } from "./Context/BookMarkContext";
import { AuthProvider } from "./Context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" />
        <title>Ecommerce BookShelf</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={inter.className}>
        <AuthProvider>
        <BookMarkProvider>
        {children}

        </BookMarkProvider>
        </AuthProvider>
        </body>
    </html>
  );
}
